pipeline:
  identifier: Build_Verademo_Fix_1693612300718
  name: Build Verademo_Fix
  orgIdentifier: default
  projectIdentifier: Verademo
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1693612209080
        repoName: VGuglielmoVeracode/Verademo_Fix
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    image: plugins/docker
                    settings:
                      dry_run: "true"
                      repo: hello/world
                      tags: latest
                  timeout: ""
                  type: Plugin
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
