pipeline:
  identifier: Build_Verademo_Fix_1693612300718
  name: Build Verademo_Fix
  orgIdentifier: default
  projectIdentifier: Verademo
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1693612209080
        repoName: VGuglielmoVeracode/Verademo_Fix
  stages:
    - step:
        type: Run
        name: build
        identifier: build
        spec:
          connectorRef: account.harnessImage
          image: maven:3.8-jdk-11
          shell: Sh
          command: mvn clean package dependency:copy-dependencies
    - step:
        type: Run
        name: check dependencies
        identifier: check_dependencies
        spec:
          connectorRef: account.harnessImage
          image: maven:3.8-jdk-11
          shell: Sh
          command: mvn dependency-check:check -U -DskipTests
          reports:
            type: JUnit
            spec:
              paths:
                - /harness/target/*.xml
